UKHO/periodic-output-service

UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.API.FunctionalTests/UKHO.PeriodicOutputService.API.FunctionalTests.csproj, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.API.FunctionalTests/appsettings.json, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.sln
Hi All,
This is the initial test automation framework skeleton for POS.
Kindly review and approve.
Thanks.
=> Automation Framework Skeleton

BuildNuget.config, CodeCoverageReport.ps1, NVDSuppressions.xml, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.API.FunctionalTests/Program.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment.UnitTests/UKHO.PeriodicOutputService.Fulfilment.UnitTests.csproj, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment.UnitTests/UnitTest1.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.sln, UKHO.PeriodicOutputService/global.json, azure-pipelines.yml, test.runsettings
This PR contains following tasks:
1) Dependency checker tasks
2) Unit Test and Code coverage
3) Build and Publish Webjob Artifacts.
=> 48899-Devops Build Pipeline (CI)

azure-pipelines.yml
This PBI contains;
1) Addition of QA stage.
=> 50365 adding QA stage

UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.API.FunctionalTests/FunctionalTests/CallEssEndPoint.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.API.FunctionalTests/Helpers/CommonHelper.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.API.FunctionalTests/Helpers/Extensions.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.API.FunctionalTests/Helpers/ModelStructureCheck.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.API.FunctionalTests/Models/ExchangeSetResponseModel.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.API.FunctionalTests/UKHO.PeriodicOutputService.API.FunctionalTests.csproj, azure-pipelines.yml
Hi,
This PR consists of:
Adding FT in QAdeploy stage.
=> 51300 devops qa ft integration

azure-pipelines.yml
Hi,
This PBI consists of:
Addition of Livedeploy stage
=> 51295 - devops create live stage

NVDSuppressions.xml
Suppression of CVE-2020-1045 fleshed out and references a work item to fix it once a known fix is available.
=> CVE-2020-1045 Suppression

.github/workflows/codeql-analysis.yml
Code scanning configuration added to enable GitHub code scanning
=> Added code scanning config

NVDSuppressions.xml
Suppression work item moved from ESS project board to Abzu board, so work item reference updated in the suppression file.
=> Suppression work item ref updated

DevDeployment/src/Modules/MockWebApp/main.tf, DevDeployment/src/Modules/MockWebApp/variables.tf, DevDeployment/src/main.tf, DevDeployment/src/variables.tf, DevDeployment/templates/continuous-deployment.yml
Hi,
Added vnet integration and ip restrictions for stub webapp.
=> 54784-devops vnet integraton for stub

DevDeployment/src/Modules/MockWebApp/main.tf, DevDeployment/src/Modules/MockWebApp/variables.tf, DevDeployment/src/main.tf, DevDeployment/src/variables.tf, DevDeployment/templates/continuous-deployment.yml, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.API.FunctionalTests/FunctionalTests/POSEndToEndFunctionalScenarios.cs
Reverts UKHO/periodic-output-service#37
=> Revert "54784-devops vnet integraton for stub"

UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Helpers/FileSystemHelper.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Helpers/FssApiClient.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Helpers/IFssApiClient.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Models/Fss/FssBatchFile.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment.UnitTests/Helpers/FssApiClientTests.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment.UnitTests/Services/FssServiceTests.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment/Program.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment/Services/FssService.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment/Services/FulfilmentDataService.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment/Services/IFssService.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment/appsettings.json
=> 56278 - download file issue

DevDeployment/src/main.tf, QALiveDeployment/src/main.tf, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Utilities/FileUtility.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment.UnitTests/Services/FssServiceTests.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment.UnitTests/Services/FulfilmentDataServiceTests.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment/Configuration/FssApiConfiguration.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment/Services/EssService.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment/Services/FssService.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment/Services/FulfilmentDataService.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment/Services/IFssService.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment/appsettings.json
Configurable BU and ACL list added.
DevOps changes to update webapp appsetting
=> 56252 - pos bu and acl configuration

DevDeployment/src/Modules/Storage/main.tf, DevDeployment/src/Modules/Storage/variables.tf, DevDeployment/src/main.tf, QALiveDeployment/src/Modules/Storage/main.tf, QALiveDeployment/src/Modules/Storage/variables.tf, QALiveDeployment/src/main.tf
Hi,
added ip restrictions for storage for dev, qa and live
=> 56372- pos devops ip restrictions for storage

DevDeployment/set_qa_subnet_configuration.ps1, azure-pipelines.yml
Hi,
added azure cli task to whitelist qa webapp subnet in to mock webapp.
=> 54784 - devops changes whitelisting qa subnet into mock

DevDeployment/set_qa_subnet_configuration.ps1, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Helpers/FssApiClient.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment/settings.job, azure-pipelines.yml
Hi,
Removed hardcoded values from script and referenced to library.
Cron job expression updated to trigger the pos webjob every thursday at 1:00 AM
=> 57019 - devops removing hardcoded values from script

UKHO.FmEssFssMock.API/UKHO.FmEssFssMock.API/Services/FileShareService.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.API.FunctionalTests/Helpers/GetBatchDetails.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.API.FunctionalTests/Helpers/TestConfiguration.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.API.FunctionalTests/Models/ResponseBatchStatusModel.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.API.FunctionalTests/appsettings.json, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Utilities/FileUtility.cs
1. Mime type issue for ISO and SHA1 files resolved 
2. SHA1 file issue resolved
=> sha1 file issue fix

UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment/settings.job
Updated the settings.job config for the web job to set CRON config to every Thursday at 8am
=> Changed CRON settings for the webjob to fire every Thursday at 8am

NVDSuppressions.xml
Updated security suppressions for the 20221010a release
=> Updated NVDSuppressions.xml

azure-pipelines.yml
removed swapping of web job configuration task from live stage
=> removed unwanted task from live stage

azure-pipelines.yml
=> added webjob configuration task for live

UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment/settings.job
ABZU-70821-update schedule time to run on Friday #70821
=> ABZU-70821-update schedule time to run on Friday AB#70821

UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Configuration/EssApiConfiguration.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Configuration/FleetManagerApiConfiguration.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Configuration/FssApiConfiguration.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Configuration/IEssApiConfiguration.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Configuration/IFleetManagerApiConfiguration.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Configuration/IFssApiConfiguration.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Models/Ess/Response/ExchangeSetResponseModel.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Models/Fm/Response/FleetManagerGetCatalogueResponseModel.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Models/Fm/Response/FleetMangerGetAuthTokenResponseModel.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Models/Fss/Request/AddFileToBatchRequestModel.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Models/Fss/Response/CreateBatchResponseModel.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Models/Fss/Response/FssBatchStatusResponseModel.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Services/EssService.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Services/FleetManagerService.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Services/FssService.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Services/IEssService.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Services/IFleetManagerService.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Services/IFssService.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/UKHO.PeriodicOutputService.Common.csproj, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment.UnitTests/Helpers/EssApiClientTests.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment.UnitTests/Services/EssServiceTests.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment.UnitTests/Services/FleetManagerServiceTests.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment.UnitTests/Services/FssServiceTests.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment.UnitTests/Services/FulfilmentDataServiceTests.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment/Program.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment/Services/FulfilmentDataService.cs
Restructured the project by 
1) Moving the files to a common project which will be used by AIO.
2) Namespaces changed as per the file location
=> 76007 - restructuring pos for aio

UKHO.PeriodicOutputService/UKHO.AdmiraltyInformationOverlay.Fulfilment/AioFulfilmentJob.cs, UKHO.PeriodicOutputService/UKHO.AdmiraltyInformationOverlay.Fulfilment/Program.cs, UKHO.PeriodicOutputService/UKHO.AdmiraltyInformationOverlay.Fulfilment/UKHO.AdmiraltyInformationOverlay.Fulfilment.csproj, UKHO.PeriodicOutputService/UKHO.AdmiraltyInformationOverlay.Fulfilment/appsettings.json, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Logging/EventIds.cs
- Added configuration related to Azure Event Hub, Application Insights,  KeyVault and Serilog.
=> 74378  -aio webjob logging and config

DevDeployment/src/main.tf, NVDSuppressions.xml, QALiveDeployment/src/main.tf, QALiveDeployment/src/variables.tf, QALiveDeployment/templates/continuous-deployment.yml, QALiveDeployment/terraform_conditional_run.ps1, UKHO.PeriodicOutputService/UKHO.AdmiraltyInformationOverlay.Fulfilment/AioFulfilmentJob.cs, UKHO.PeriodicOutputService/UKHO.AdmiraltyInformationOverlay.Fulfilment/Program.cs, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment/UKHO.PeriodicOutputService.Fulfilment.csproj
Abzu-Added missing argument
Abzu-Corrected apm labels for AIO
Fixed APM environment setting issue
Update suppresion
Update problematic package
=> Abzu-Added missing terraform config

UKHO.PeriodicOutputService/UKHO.BESS.ConfigurationService/Program.cs, UKHO.PeriodicOutputService/UKHO.BESS.ConfigurationService/UKHO.BESS.ConfigurationService.csproj, UKHO.PeriodicOutputService/UKHO.BESS.ConfigurationService/appsettings.json, UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.sln
BESS Project Skeleton Creation for Configuration Service, under POS.
[PBI 139799](https://dev.azure.com/ukhydro/Exchange%20Set%20Service/_workitems/edit/139799)
=> 139799 - Bespoke Exchange Set Configuration Service Project Skeleton Creation

DevDeployment/src/main.tf, DevDeployment/templates/continuous-deployment.yml, QALiveDeployment/src/main.tf, QALiveDeployment/templates/continuous-deployment.yml, UKHO.PeriodicOutputService/UKHO.BESS.API.FunctionalTests/appsettings.json, azure-pipelines.yml, vNextE2EDeployment/src/main.tf, vNextE2EDeployment/templates/continuous-deployment.yml, vNextIATDeployment/src/main.tf, vNextIATDeployment/templates/continuous-deployment.yml
PR contains changes in Webapp Service Module for setting environment variables **(container name**) for POS webapp. 
Tweaked variables in library and passed the same to YAML for Swapping configuration.
(fixed incorrect mapping of library variables to container name)
=> BESS Configuration Service Webjob observation fix

Deployment/check_service_status_webjob.ps1, Deployment/src/Modules/WebApp/main.tf, Deployment/src/Modules/WebApp/variables.tf, Deployment/src/main.tf, Deployment/src/migrate.tf, Deployment/src/outputs.tf, Deployment/src/variables.tf, Deployment/templates/continuous-deployment.yml, Deployment/terraform_conditional_run.ps1, PeriodicOutputService.sln, azure-pipelines.yml
Terraform and pipeline changes to use deployment slots.
=> Use deployment slots

Deployment/check_service_status_webjob.ps1, Deployment/src/Modules/WebApp/main.tf, Deployment/src/Modules/WebApp/variables.tf, Deployment/src/main.tf, Deployment/src/migrate.tf, Deployment/src/outputs.tf, Deployment/src/variables.tf, Deployment/templates/continuous-deployment.yml, Deployment/terraform_conditional_run.ps1, PeriodicOutputService.sln
=> Update from main 17/04/2025
